### PR TITLE
TypoFix slide `active` field was `status`

### PR DESCRIPTION
**Pull request by arturmamedov**
You can merge this to 2.0 branch to, or if you want i continue to create a pull-requests for booth branches

### CODE REVIEW

**Comment by becquerel** [comment]
@arturmamedov thanks for fixing the bug. As for the unary operators, since PSR does not specify this, I tend to follow Symfony coding standards in the code, that put unary operators right next to the affected value:
http://symfony.com/doc/current/contributing/code/standards.html
i.e. correct: `if (!$x)`, incorrect (though used in some projects) `if ( ! $x)`
I would like to keep it that way in the Slider module to keep the code consistent, can you please revert those changes ?

**Comment by becquerel** [comment]
@arturmamedov also, if you could make PR for both master and 2.0 branch, it would make it easier for me to merge. I will probably drop support for new features in the near future, but right now, separate PRs for both branches would be greatly appreciated

**Comment by arturmamedov** [comment]
@becquerel i use PhpStorm and the https://github.com/michaeldyrynda/phpstorm-laravel-code-style 
what kind of automation you use for format code? There are a PHP CS Fixer or something, for format before commit?

**Comment by becquerel** [comment]
I believe I just use default PHPStorm formatting for PHP with PHP Code Sniffer validation set to PSR-2. I don't use any automated tool to autofix the code though.

**Comment by arturmamedov** [comment]
@becquerel I reverted the code style

**Comment by becquerel** [comment]
@arturmamedov thank you

**Pull request merged**
