### PR TITLE
Adds Validation for title and caption in Creating Slide

### PR DESCRIPTION
**Pull request by ikashifullah**
@becquerel, I have pushed a few changes. And commit will allow slides to at least have **Title** and **Caption** be filled.

### CODE REVIEW

**Comment by Fisiu** [comment]
In my opinion, title and caption should not be required at all. What if you want to display plain images on your slider?

**Comment by ikashifullah** [comment]
@Fisiu, yes. that makes sense. :+1:

**Comment by becquerel** [comment]
@Fisiu yes ... did not think of that, and makes sense, I actually have few sliders like that. I usually have custom template, I rarely use the generic one, but it totally makes sense not to validate the inputs here

**Comment by becquerel** [comment]
@kashifullahwebdeveloper thanks again, but due to this, I'm gonna close the issue/PR

**Pull request closed without merging**
