### PR TITLE
Compatibility with AsgardCMS 2.0

### PR DESCRIPTION
**Pull request by imagina**

### CODE REVIEW

**Comment by arturmamedov** [comment]
Why not merge this?

**Comment by becquerel** [comment]
@arturmamedov I was waiting for the issues in pull request to be fixed, and did not have time to do it myself yet (see my comments above)

**Comment by arturmamedov** [comment]
@becquerel sorry i not see what issue, can you link me it, maybe i can help. In my fork i add this pull request with patch and all work great on AsgardCMS 2.0 now i go to change some thing with file upload are you interested in contribution, how i need to preoced?

**Comment by becquerel** [comment]
@arturmamedov the issues are actually commented in the code above. It is just coding style, not affecting functionality, but I wanted to keep whole module as close to PSR as possible. I will merge these today and fix the coding style myself, and feel free to make a pull request from your fork if you like to contribute. Thank you !

**Pull request merged**
