### PR TITLE
BugFix of apiRoutes, the right middleware to use is `token-can`

### PR DESCRIPTION
**Pull request by arturmamedov**
`token-can` use User TokenCan middleware, `can` use  Core Authorization.

### CODE REVIEW

**Comment by arturmamedov** [comment]
And i think that the slide named routes are wrong formatted, it must be `admin.slider.slide.update` and `api.slider.slide.update` , what you think?

**Comment by becquerel** [comment]
you are right about route names, thank you, I will make a separate issue for this

**Comment by arturmamedov** [comment]
@becquerel if you want i can do a pull-request for this, i have other suggestion i can create a issue with proposals?

**Comment by becquerel** [comment]
@arturmamedov please feel free to create as many issues as you see fit. Though the work on this module has been kind of stale for last couple months (I don't have much time for it and it does what I need it to do), I am open to making improvements

**Pull request merged**
